### ISSUE TITLE
AddClass.java is now deprecated 

### ISSUE THREAD

**Issue by MattFossett** [mucs420f19/MMouseLLC#115]
cleaner functions in UMLEnvironment should now be used, remove dependency on this badly titled class that not only adds classes but also edits and finds.

Estimated: 1-2 hours
Actual- 
  Matt: 1 hour
  Dan did the rest of this in the refactor issue, see issue #123 
Primary: Matt (Unless someone notices this and wants to do it)

**Comment by djharten** [comment]
AddClass removed from all Console related tasks. Still needs to be removed in GUI.
