### ISSUE TITLE
GUI - Plus, Minus, and edit buttons 

### ISSUE THREAD

**Issue by ehinerdeer** [mucs420f19/MMouseLLC#153]
Buttons should be added next to the name, attributes for add edit and delete to minimize the space required at the bottom of the gui tile. these buttons should link to its specific attribute and change the name or each. 

Primary-Lauren
Alt- Grant
Estimated: 10 hours or more

Actual time: 23.5 hours

**Comment by lndeaver** [comment]
Logged time: 
10/24
Looked at JavaFx work - 1.5 hours

10/25
Looked at JavaFx work - 2.0 hours

10/28
JavaFx research - 3 hours

10/29
JavaFx research - 2.5 hours

10/30
Looked at GUI code - 0.5 hours

10/31
Worked on edit/display buttons for GUI - 2.5 hours in lab, 1.5 hours after classes

11/4
Worked on edit/display buttons again - 3 hours

11/5
Worked on edit/display buttons (again again) - 4 hours

**Comment by lndeaver** [comment]
logged time:
11/7
fixed arrow updating issue - 2 hours

11/8 
finished fixing the buttons updating right - 1 hour
