### ISSUE TITLE
(GUI) Display Attributes in new implimentation

### ISSUE THREAD

**Issue by MattFossett** [mucs420f19/MMouseLLC#164]
Attributes are no longer simply bullet points, but now of 2 forms. 
Fields:
type varName
EX: int height

Functions: 
returnType functionName
EX: int getHeight()

As of 11/6 the Visibility of Members issue is not done. Once that is done, the model will have information for private/public/protected as well. 

EX: 
private int height
private String name
public int getHeight()
public String getName()

The UMLItem class keeps track of these changes so it will be similar to the old implementation.

**Comment by lndeaver** [comment]
Log time:
11/22
got add button working with logic - 4 hours
11/25
got remove button working with logic - 4 hours
11/26
got edit button working with logic - 4 hours
fixed input checking and dialog boxes - 4 hours
11/27
fixed a bug with input checking - 2 hours
12/3
added comments - 1 hour
