### ISSUE TITLE
Check Extra Arguments

### ISSUE THREAD

**Issue by ehinerdeer** [mucs420f19/MMouseLLC#69]
when adding in the console there should be a way to add more than one class in the single line argument. Example: 

"add eric matt dan grant kasey lauren" should result in ->

[ eric matt dan grant kasey lauren ] for the list in the environment

**Comment by djharten** [comment]
With the JLine API I used for tab completion this was a pleasant side effect. I just added loops to each spot where this would be necessary, and it now works. Closing issue.
