### ISSUE TITLE
Tab Completion

### ISSUE THREAD

**Issue by ehinerdeer** [mucs420f19/MMouseLLC#70]
add Tab Completion for if i hit "a" then TAB, console should finish to "add" and so on for each command.

Estimated: 2 hours
Primary- Dan
Secondary- Lauren

**Comment by djharten** [comment]
Looking at JLine(great tool btw, thank you), I'd say that properly using this will involve a relatively large refactor of existing code in Console. Updating estimated time to be 4 hours.

**Comment by djharten** [comment]
Tab Completion finished. Was more difficult than expected. 8 hours.
